# Generated by Django 5.1.4 on 2024-12-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_department_alter_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eligibility',
            field=models.TextField(blank=True, null=True),
        ),
    ]
